name: igr
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - plotly
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _pytorch_select=0.2
  - blas=1.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - cloudpickle=2.0.0
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cudatoolkit=10.2.89
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2021.10.0
  - dbus=1.13.18
  - expat=2.6.4
  - ffmpeg=4.3
  - fftw=3.3.9
  - fontconfig=2.14.1
  - freetype=2.12.1
  - fsspec=2022.11.0
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gnutls=3.6.15
  - gputil=1.4.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - imageio=2.9.0
  - intel-openmp=2021.4.0
  - jpeg=9b
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libaec=1.1.3
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcurl=8.2.1
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnghttp2=1.52.0
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.0.9
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.48.0
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.9.14
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.4
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=2.6.3
  - ninja=1.12.1
  - ninja-base=1.12.1
  - numpy-base=1.19.2
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1w
  - packaging=22.0
  - partd=1.2.0
  - pcre2=10.42
  - pillow=5.4.1
  - pip=22.3.1
  - plotly=5.24.1
  - pycparser=2.21
  - pyhocon=0.3.61
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.16
  - python-dateutil=2.8.2
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pywavelets=1.3.0
  - pyyaml=6.0
  - qt=5.9.7
  - readline=8.2
  - requests=2.28.1
  - scikit-image=0.16.2
  - scipy=1.6.2
  - setuptools=65.6.3
  - sip=4.19.8
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - tenacity=8.0.1
  - tk=8.6.14
  - toolz=0.12.0
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tornado=6.2
  - trimesh=4.5.3
  - typing_extensions=4.3.0
  - urllib3=1.26.14
  - wheel=0.38.4
  - xz=5.6.4
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - numpy==1.21.6
